// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.fuchsia:
        // TODO: Handle this case.
      case TargetPlatform.linux:
        // TODO: Handle this case.
      case TargetPlatform.windows:
        // TODO: Handle this case.
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // Generate this file with credentials with the FlutterFire CLI
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNN5YNup8D5-dOXNxvlDUSl2r6QbxYQwc',
    appId: '1:675635250670:android:babe8846c3f8a6d1c37aff',
    messagingSenderId: '675635250670',
    projectId: 'flutterchatapp-88e65',
    authDomain: 'flutterchatapp-88e65.firebaseapp.com',
    databaseURL: "https://flutterchatapp-88e65-default-rtdb.firebaseio.com",
    storageBucket: 'flutterchatapp-88e65.appspot.com',
    // measurementId: 'G-E9HP9KJ8DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNN5YNup8D5-dOXNxvlDUSl2r6QbxYQwc', 
    appId: '1:675635250670:android:babe8846c3f8a6d1c37aff', 
    messagingSenderId: '675635250670', 
    projectId: 'flutterchatapp-88e65'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz3yem_dT_mnJ5ticLBV5_dnL46nfTQI4',
    appId: '1:1004971287137:web:f339ac0ee3df1a1e808020',
    messagingSenderId: '1004971287137',
    projectId: 'flutter-firebase-web-25540',
    databaseURL: "https://flutter-firebase-web-25540-default-rtdb.firebaseio.com",
    storageBucket: 'flutter-firebase-web-25540.appspot.com',
    iosClientId: 'IOS CLIENT ID',
    iosBundleId: 'com.example.BUNDLE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz3yem_dT_mnJ5ticLBV5_dnL46nfTQI4',
    appId: '1:1004971287137:web:f339ac0ee3df1a1e808020',
    messagingSenderId: '1004971287137',
    projectId: 'flutter-firebase-web-25540',
    databaseURL: "https://flutter-firebase-web-25540-default-rtdb.firebaseio.com",
    storageBucket: 'flutter-firebase-web-25540.appspot.com',
    iosClientId: 'IOS CLIENT ID',
    iosBundleId: 'com.example.BUNDLE',
  );
}